// ============================================================================
// Reports (/admin/reports)
// The five compliance exports. Each generated report records when it was made
// and by whom; the audit report carries a digital signature for the regulator.
// ============================================================================
import { useEffect, useState } from "react";
import { generateReport, getAdminDashboard, getReports } from "../../api";
import { useApp } from "../../context/AppContext";
import StatusBadge from "../../components/common/StatusBadge";
import { previewLock } from "../../config/modules";

const REPORT_TYPES = [
  {
    id: "Consent Report",
    blurb: "All consents by date range, status and purpose.",
    formats: ["PDF", "CSV"],
    signed: false,
  },
  {
    id: "DSAR Completion Report",
    blurb: "SLA compliance rate and average resolution time.",
    formats: ["PDF"],
    signed: false,
  },
  {
    id: "Grievance Report",
    blurb: "Open, resolved and escalated complaints by period.",
    formats: ["PDF"],
    signed: false,
  },
  {
    id: "Audit Report",
    blurb: "Full audit trail export with a digital signature, for submission to the Data Protection Board.",
    formats: ["PDF"],
    signed: true,
  },
  {
    id: "Retention Policy Report",
    blurb: "Purges run, records deleted, and exemptions applied.",
    formats: ["PDF"],
    signed: false,
  },
];

const RANGES = ["Last 7 days", "Last 30 days", "This month", "Last month", "This quarter", "This year"];

export default function Reports() {
  const { notify, user } = useApp();
  const [rows, setRows] = useState([]);
  const [range, setRange] = useState("Last 30 days");
  const [busy, setBusy] = useState(null);
  const [summary, setSummary] = useState(null);

  const load = () => getReports().then(setRows);

  useEffect(() => {
    load();
    getAdminDashboard().then((d) => setSummary(d.stats));
  }, []);

  const make = async (type, format, signed) => {
    setBusy(type + format);
    try {
      const row = await generateReport({ type, range, format, signed, by: user?.id });
      await load();
      // Produce a real file so the button isn't decorative.
      const body =
        `${type}\nRange: ${range}\nGenerated: ${row.generated_at}\nGenerated by: ${row.generated_by}\n` +
        (signed ? `Digital signature: sha256:${Math.abs(Date.parse(row.generated_at)).toString(16)}...\n` : "") +
        `\n--- summary ---\n${JSON.stringify(summary, null, 2)}\n`;
      const blob = new Blob([body], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${type.replace(/\s+/g, "-").toLowerCase()}.${format.toLowerCase()}`;
      a.click();
      URL.revokeObjectURL(url);
      notify(`${type} generated as ${format}.`);
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-ink">Reports</h1>
          <p className="text-sm text-muted">
            Compliance-ready exports. Everything generated here is itself logged.
          </p>
        </div>
        <div>
          <label className="label" htmlFor="r-range">Date range</label>
          <select id="r-range" className="input" value={range} onChange={(e) => setRange(e.target.value)}>
            {RANGES.map((r) => <option key={r} value={r}>{r}</option>)}
          </select>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {REPORT_TYPES.map((r) => (
          <div key={r.id} className="card flex flex-col p-5">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <h2 className="font-semibold text-ink">{r.id}</h2>
              {r.signed && (
                <span className="inline-flex items-center gap-1 rounded-full bg-navy/10 px-2 py-0.5 text-xs font-semibold text-navy">
                  <span aria-hidden="true">🔒</span> digitally signed
                </span>
              )}
            </div>
            <p className="mt-1 flex-1 text-sm text-muted">{r.blurb}</p>
            <div className="mt-4 flex flex-wrap gap-2">
              {r.formats.map((f) => (
                <button
                  key={f}
                  type="button"
                  className="btn-secondary"
                  onClick={() => make(r.id, f, r.signed)}
                  disabled={busy === r.id + f}
                  {...previewLock("reports", "Generating a report")}
                >
                  {busy === r.id + f ? "Generating…" : `Generate ${f}`}
                </button>
              ))}
            </div>
          </div>
        ))}
      </div>

      <section className="card overflow-hidden">
        <div className="border-b border-line px-5 py-4">
          <h2 className="font-semibold text-ink">Generated reports</h2>
          <p className="text-xs text-muted">
            Timestamp, who generated it, and the download.
          </p>
        </div>
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-line">
            <thead className="bg-canvas">
              <tr>
                <th className="th">Report</th>
                <th className="th">Range</th>
                <th className="th">Format</th>
                <th className="th">Signature</th>
                <th className="th">Generated</th>
                <th className="th">By</th>
                <th className="th sr-only">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {rows.length === 0 && (
                <tr><td className="td text-center text-muted" colSpan={7}>Nothing generated yet.</td></tr>
              )}
              {rows.map((r) => (
                <tr key={r.id}>
                  <td className="td">{r.type}</td>
                  <td className="td text-xs text-muted">{r.range}</td>
                  <td className="td"><span className="tag">{r.format}</span></td>
                  <td className="td">
                    {r.signed
                      ? <StatusBadge status="valid" label="Signed" />
                      : <span className="text-xs text-muted">—</span>}
                  </td>
                  <td className="td text-xs text-muted">
                    {new Date(r.generated_at).toLocaleString()}
                  </td>
                  <td className="td font-mono text-xs">{r.generated_by}</td>
                  <td className="td">
                    <button type="button" className="text-sm text-teal underline"
                            onClick={() => make(r.type, r.format, r.signed)}>
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
